site_name: Scrape Schema
site_description: Converting any text (xml, html, plain text, stdout, etc) to python datatypes
strict: true
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: dark blue
      accent: dark blue
      toggle:
        icon: material/lightbulb-outline
        name: "Switch to dark mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: dark blue
      accent: dark blue
      toggle:
        icon: material/lightbulb
        name: "Switch to light mode"


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences

nav:
  - Hub: index.md
  - Russian:
    - Minimal app: RU/minimal_app.md
    - Usage: RU/usage.md
    - Tutorial: RU/tutorial.md
    - Advanced: RU/advanced.md
  - English:
    - Minimal app: EN/minimal_app.md
    - Usage: EN/usage.md
    - Tutorial: EN/tutorial.md
    - Advanced: EN/advanced.md