Set Shell bash
Set TypingSpeed 0.1
Sleep 1s
Type "python3 bp_main_app.py"
Enter
Sleep 1s
Tab
Sleep 500ms
Down
Sleep 500ms
Enter
Sleep 1s
Tab
Down 2
Enter
Sleep 1s
Tab
Sleep 500ms
Down 4
Enter
Sleep 1.5s
Down 23
Sleep 1s
Type "q"
Sleep 1s
Tab
Sleep 500ms
Escape
Type "[A "
Down
Sleep 1s
Enter
Sleep 500ms
Tab
Escape
Type "[A"
Sleep 500ms
Type " "
Down 2
Sleep 500ms
Enter
Sleep 1s
Type "e"
Down
Enter
Type "y"
Sleep 500ms

