Set Shell bash
Set TypingSpeed 0.1
Type "python3 minimal_app.py"
Enter
Sleep 500ms
Tab 2
Type " test123 hw!! "
Sleep 500ms
Type "12000"
Enter
Sleep 500ms
Type "h"
Sleep 500ms
Escape
Type "[B"
Sleep 500ms
Type " e"
Escape
Type "[B"
Enter
Type "\"
Sleep 1.5s
Backspace
Sleep 1s
Type "he"
Escape
Type "[B"
Enter
Sleep 500ms
Escape
Type "[B"
Escape
Type "[B"
Escape
Type "[B"
Escape
Type "[B"
Escape
Type "[Bqe"
Escape
Type "[B"
Escape
Type "[B"
Enter
Type "y"
Sleep 1.5s
