Set Shell bash
Set TypingSpeed 0.1
Type "python3 usage_default_arguments.py"
Enter
Sleep 500ms
Tab 2
Type " "
Sleep 1s
Enter
Sleep 500ms
Type "hell"
Sleep 500ms
Type "o georgiy"
Enter
Tab
Sleep 500ms
Tab 3
Enter
Sleep 500ms
Escape
Type "[B"
Escape
Type "[B"
Escape
Type "[B"
Escape
Type "[B"
Escape
Type "[B"
Escape
Type "[B"
Escape
Type "[Bw"
Sleep 500ms
Type "qe"
Escape
Type "[B"
Enter
Sleep 500ms
Type "y"
Sleep 500ms

