Set Shell bash
Set TypingSpeed 0.1
Sleep 1s
Type "python3 usage_shortcuts.py"
Enter
Sleep 500ms
Tab
Sleep 500ms
Tab
Enter
Sleep 500ms
Tab 3
Sleep 1s
Enter
Sleep 500ms
Type "asdasda"
Backspace 7
Type "10.0"
Backspace 2
Type "0002"
Enter
Sleep 500ms
Tab
Sleep 500ms
Tab 3
Enter
Tab
Sleep 500ms
Tab 5
Sleep 500ms
Enter
Sleep 500ms
Escape
Type "[B"
Escape
Type "[B"
Escape
Type "[B"
Escape
Type "[B"
Escape
Type "[B"
Escape
Type "[B"
Escape
Type "[B"
Sleep 500ms
Type "q"
Ctrl+C
Ctrl+C

